{% set name = "oidc-agent" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/indigo-dc/oidc-agent/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c8c2cb6c70e4e74a2be452d6238171947fab2da7920308f11c9bbe39669f4850
  patches:
    - 0001-Disable-oidc-prompt.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
    - sed
    - help2man
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libsodium
    - libcurl
    - libmicrohttpd
    - libqrencode
    - libseccomp  # [linux]
    - libsecret
    - glib
    - argp-standalone  # [osx]
    - zlib

test:
  commands:
    - oidc-agent --help
    - oidc-agent-server --help
    - oidc-gen --help
    - oidc-add --help
    - oidc-token --help
    - test -f "$PREFIX/lib/liboidc-agent.so.4"  # [linux]
    - test -f "$PREFIX/lib/liboidc-agent.4.dylib"  # [osx]

about:
  home: https://indigo-dc.gitbook.io/oidc-agent/
  license: MIT
  license_file: LICENSE
  summary: 'Tools to manage OpenID Connect tokens from the command line'
  doc_url: https://indigo-dc.gitbook.io/oidc-agent/
  dev_url: https://github.com/indigo-dc/oidc-agent/

extra:
  recipe-maintainers:
    - chrisburr
