{% set name = "oidc-agent" %}
{% set version = "4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/indigo-dc/oidc-agent/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 02a71e8ad3ba58870429b271f9632ffdfcd570586213ddfb014c12733be3559e
  patches:
    - 0001-Disable-oidc-prompt.patch
    - 0002-Fix-macos-build.patch
    - 0003-Use-pkg-config-to-find-more-libraries.patch
    - 0004-Use-LDFLAGS-for-linking-on-macOS.patch
    - 0005-Set-install_name-for-liboidc-agent.4.dylib-on-macOS.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
    - sed
    - help2man
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libsodium
    - libcurl
    - libmicrohttpd
    - libqrencode
    - libseccomp  # [linux]
    - libsecret
    - glib
    - argp-standalone  # [osx]
    - zlib

test:
  commands:
    - oidc-agent --help
    - oidc-gen --help
    - oidc-add --help
    - oidc-token --help
    - test -f "$PREFIX/lib/liboidc-agent.so.4"  # [linux]
    - test -f "$PREFIX/lib/liboidc-agent.4.dylib"  # [osx]

about:
  home: https://indigo-dc.gitbook.io/oidc-agent/
  license: MIT
  license_file: LICENSE
  summary: Tools to manage OpenID Connect tokens from the command line
  doc_url: https://indigo-dc.gitbook.io/oidc-agent/
  dev_url: https://github.com/indigo-dc/oidc-agent/

extra:
  recipe-maintainers:
    - chrisburr
