{% set name = "oidc-agent" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/indigo-dc/oidc-agent/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0a61b56ac2ef06105a7d8f8fd8bd4bc31b4836097caa6575ad4597287bd7f872
  patches:
    - 0001-Fix-compiler-variables.patch
    - 0002-Try-to-fix-macOS.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - sed
    - help2man
  host:
    - libsodium
    - libcurl
    - libmicrohttpd
    - libseccomp  # [linux]
    - libsecret
    - glib
    - argp-standalone  # [osx]

test:
  commands:
    - oidc-agent --help
    - oidc-agent-server --help
    - oidc-gen --help
    - oidc-add --help
    - oidc-token --help
    - test -f "$PREFIX/lib/liboidc-agent.so.4"  # [linux]
    - test -f "$PREFIX/lib/liboidc-agent.4.dylib"  # [osx]

about:
  home: https://indigo-dc.gitbook.io/oidc-agent/
  license: MIT
  license_file: LICENSE
  summary: Tools to manage OpenID Connect tokens from the command line
  doc_url: https://indigo-dc.gitbook.io/oidc-agent/
  dev_url: https://github.com/indigo-dc/oidc-agent/

extra:
  recipe-maintainers:
    - chrisburr
